using SilentScan.Core.Reporting.RuleHarness.Adapters;

namespace SilentScan.Core.Reporting.RuleHarness;

public static class RuleRegistry
{
    public static IReadOnlyList<IRule> All { get; } =
    [
        new WaitForRule(),
        new CursorCloseOnCommitRule(),
        new CompositeIndexLeadingColumnRule(),
        new MissingStatisticsRule(),
        new SessionDateSettingRule(),
        new AmbiguousDateLiteralConversionRule(),
        new CartesianJoinRule(),
        new OuterJoinPredicateCollapseRule(),
        new TruncateSwallowedRule(),
        new CatchAllPredicateRule(),
        new BareTopNoOrderByRule(),
        new StringAggMissingOrderRule(),
        new ForXmlPathMissingOrderRule(),
        new JsonArrayAggMissingOrderRule(),
        new JsonObjectDuplicateKeyRule(),
        new UnistrUnpairedSurrogateRule(),
        new RegexpReplaceDollarBackreferenceRule(),
        new RegexpDefaultCaseSensitiveOnCiColumnRule(),
        new RegexpAccentInsensitiveColumnRule(),
        new StringConcatNullRule(),
        new TvfCallArgumentMismatchRule(),
        new ParameterReassignmentPredicateRule(),
        new NotInNullableSubqueryRule(),
        new NonUniqueUpdateSourceRule(),
        new CheckConstraintPredicateContradictionRule(),
        new FloatEqualityPredicateRule(),
        new FloatOrderDependentAggregateRule(),
        new IndexCoverageRule(),
        new SelfReferencingDmlRule(),
        new TransactionHygieneRule(),
        new DynamicDataMaskingRule(),

        new ModuleCompileFlagRule(),
        new WindowFrameRule(),
        new BoundedStringBuiltinTruncationRule(),
        new ViewOrderingRule(),
        new IndexHintRule(),
        new CodeMetricRule(),
        new FormattingRule(),
        new NamingRule(),
        new DeadCodeRule(),
        new DuplicationRule(),
        new DeprecatedSyntaxRule(),
        new ControlFlowRiskRule(),
        new QueryAntiPatternRule(),
        new TriggerCorrectnessRule(),
        new ForcedSerialRule(),
        new SetOptionRule(),

        new PartialCompositeForeignKeyJoinRule(),
        new StatementShapeRule(),
        new MultiReferencedCteRule(),
        new PostExpansionJoinWidthRule(),
        new SelectStarViewRule(),
        new OutputParameterRule(),
        new UnindexedTempTableUsageRule(),

        new AnsiPaddingOffColumnRule(),
        new TriggerOrderRule(),
        new ProcCallArgumentMismatchRule(),
        new ProcCallTableValuedArgumentMismatchRule(),
        new SpExecuteSqlParameterMismatchRule(),
        new MaxTypedColumnRule(),
        new MemoryOptimizedSchemaOnlyDurabilityRule(),
        new NonPersistedComputedColumnRule(),
        new UntrustedConstraintRule(),
        new CheckConstraintRule(),
        new SecurityPredicateIndexRule(),
        new DefaultNullableConstraintRule(),
        new CascadingForeignKeyRule(),
        new TemporalTableHistoryIndexGapRule(),
        new NestedViewDepthRule(),

        new CrossModuleLockOrderRule(),
        new TriggerRecursionCycleRule(),

        new TvfFenceRule(),
        new ScalarUdfRule(),
        new SecurityRule(),
    ];
}
