using System.CommandLine;
using System.Text.Json;
using Microsoft.Data.SqlClient;

namespace SilentScan.Verify.Commands;

public static class GenerateCollationCodePagesCommand
{
    private static readonly JsonSerializerOptions JsonOptions = new() { WriteIndented = true };

    public static Command Create()
    {
        var outputOption = new Option<string>("--output")
        {
            Description = "Path to write the collation code page JSON to.",
            DefaultValueFactory = _ => "src/SilentScan.Core/TypeInference/CollationCodePages.json",
        };

        var command = new Command("generate-collation-codepages", "Probe the Docker SQL Server oracle for every collation's non-Unicode code page and write the checked-in JSON.");
        command.Options.Add(outputOption);

        command.SetAction(async (parseResult, cancellationToken) =>
        {
            var output = parseResult.GetValue(outputOption)!;
            return await RunAsync(output, SqlServerOptions.LocalDockerLatest, Console.Out, cancellationToken);
        });

        return command;
    }

    internal static async Task<int> RunAsync(string outputPath, SqlServerOptions sqlOptions, TextWriter stdout, CancellationToken cancellationToken = default)
    {
        await using var connection = new SqlConnection(sqlOptions.BuildConnectionString());
        await connection.OpenAsync(cancellationToken);

        string serverVersion;
        await using (var versionCommand = new SqlCommand("SELECT SERVERPROPERTY('ProductVersion')", connection))
        {
            serverVersion = (string)(await versionCommand.ExecuteScalarAsync(cancellationToken))!;
        }

        var codePages = new SortedDictionary<string, int>(StringComparer.Ordinal);
        await using (var command = new SqlCommand(
            "SELECT name, COLLATIONPROPERTY(name, 'CodePage') AS CodePage FROM sys.fn_helpcollations() ORDER BY name;", connection))
        await using (var reader = await command.ExecuteReaderAsync(cancellationToken))
        {
            while (await reader.ReadAsync(cancellationToken))
            {
                var name = reader.GetString(0);
                if (reader.IsDBNull(1))
                {
                    continue;
                }

                codePages[name] = reader.GetInt32(1);
            }
        }

        var document = new
        {
            ServerVersion = serverVersion,
            ProbedAtUtc = DateTime.UtcNow.ToString("yyyy-MM-dd", System.Globalization.CultureInfo.InvariantCulture),
            Notes = "Generated by SilentScan.Verify generate-collation-codepages against the local Docker SQL Server, from sys.fn_helpcollations() joined to COLLATIONPROPERTY(name, 'CodePage'). "
                + "Every entry is a non-Unicode code page (Windows codepage id, or 65001 for a _UTF8 collation) that char/varchar storage under that collation uses; it is what WriteLossClassifier checks a Unicode literal's characters against before claiming an implicit Unicode-to-non-Unicode write silently replaces them with '?'.",
            CodePages = codePages,
        };

        var json = JsonSerializer.Serialize(document, JsonOptions);
        await File.WriteAllTextAsync(outputPath, json + Environment.NewLine, cancellationToken);
        await stdout.WriteLineAsync($"Wrote {codePages.Count} entries (server {serverVersion}) to {outputPath}");

        return 0;
    }
}
